alias ll='ls -lah'
alias be='bundle exec'
alias ber='bundle exec spring rspec'
alias go='git checkout'
alias gb='git branch'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gcg='git commit -am "$(curl -s http://whatthecommit.com/index.txt)"'
alias gup='git pull'
alias gp='git push'
alias gbclear='git branch --merged master | grep -v 'master$' | xargs git branch -d'
alias hclear='rm ~/.zsh_history ~/.pry_history ~/.psql_history ~/.bash_history'
alias con='discon && ~/tunnelblick.rb connect'
alias discon='export TUNNELBLICK_USER=ivan.zotov && ~/tunnelblick.rb disconnect_all'
alias py='python3'
