#!/usr/bin/env zsh

if [ ! -d ~/.oh-my-zsh ]; then
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
fi

cd `dirname $0`
dotfiles=$(pwd)

cat ~/.zshrc | grep "$dotfiles/zshrc" || echo "source ${dotfiles}/zshrc" >> ~/.zshrc
cat ~/.zshrc | grep "oh-my-zsh" || echo "source ~/.oh-my-zsh/oh-my-zsh.sh" >> ~/.zshrc

source ~/.zshrc

[ -f ~/.gemrc ] || cp $dotfiles/gemrc ~/.gemrc
